// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-axios';
import type { ReadRootGetData, ApiCheckoutApiCheckoutPostData, ApiCheckoutApiCheckoutPostError, GetPaymentApiPaymentPostData, GetPaymentApiPaymentPostError, LoginApiLoginPostData, LoginApiLoginPostError, GetAirportApiGetAirportGetData, GetTestApiTestGetData, GetFlightApiSearchFlightGetData, GetFlightApiSearchFlightGetError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Read Root
 */
export const readRootGet = <ThrowOnError extends boolean = false>(options?: Options<ReadRootGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

/**
 * Api Checkout
 */
export const apiCheckoutApiCheckoutPost = <ThrowOnError extends boolean = false>(options: Options<ApiCheckoutApiCheckoutPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, ApiCheckoutApiCheckoutPostError, ThrowOnError>({
        url: '/api_checkout',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Payment
 */
export const getPaymentApiPaymentPost = <ThrowOnError extends boolean = false>(options: Options<GetPaymentApiPaymentPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, GetPaymentApiPaymentPostError, ThrowOnError>({
        url: '/api_payment',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Login
 */
export const loginApiLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginApiLoginPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, LoginApiLoginPostError, ThrowOnError>({
        url: '/api_login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Airport
 */
export const getAirportApiGetAirportGet = <ThrowOnError extends boolean = false>(options?: Options<GetAirportApiGetAirportGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
        url: '/api_get_airport',
        ...options
    });
};

/**
 * Get Test
 */
export const getTestApiTestGet = <ThrowOnError extends boolean = false>(options?: Options<GetTestApiTestGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
        url: '/api_test',
        ...options
    });
};

/**
 * Get Flight
 */
export const getFlightApiSearchFlightGet = <ThrowOnError extends boolean = false>(options: Options<GetFlightApiSearchFlightGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, GetFlightApiSearchFlightGetError, ThrowOnError>({
        url: '/api_search_flight',
        ...options
    });
};