// This file is auto-generated by @hey-api/openapi-ts

export type ApiCheckout = {
    id: string;
};

export type Airport = {
    name: string;
    address: string;
    code: string;
};

export type GetPayment = {
    flight_id: string;
    passenger: Passenger;
    contact: GetPaymentContact;
};

export type GetPaymentContact = {
    prefix: string;
    name: string;
    lastname: string;
    email: string;
    countryCode: string;
    phoneNumber: string;
};

export type GetPaymentIdentity = {
    type: string;
    number: string;
    out_date: string;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type LoginModel = {
    username: string;
    password: string;
};

export type Passenger = {
    name: string;
    lastname: string;
    gender: string;
    country: string;
    birthday: string;
    identityType: GetPaymentIdentity;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApiCheckoutApiCheckoutPostData = {
    body: ApiCheckout;
    path?: never;
    query?: never;
    url: '/api/checkout';
};

export type ApiCheckoutApiCheckoutPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiCheckoutApiCheckoutPostError = ApiCheckoutApiCheckoutPostErrors[keyof ApiCheckoutApiCheckoutPostErrors];

export type ApiCheckoutApiCheckoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPaymentApiPaymentPostData = {
    body: GetPayment;
    path?: never;
    query?: never;
    url: '/api/payment';
};

export type GetPaymentApiPaymentPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPaymentApiPaymentPostError = GetPaymentApiPaymentPostErrors[keyof GetPaymentApiPaymentPostErrors];

export type GetPaymentApiPaymentPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LoginApiAuthLoginPostData = {
    body: LoginModel;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginApiAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiAuthLoginPostError = LoginApiAuthLoginPostErrors[keyof LoginApiAuthLoginPostErrors];

export type LoginApiAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAirportsApiAirportGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/airport';
};

export type GetAirportsApiAirportGetResponses = {
    /**
     * Successful Response
     */
    200: Array<Airport>;
};

export type GetAirportsApiAirportGetResponse = GetAirportsApiAirportGetResponses[keyof GetAirportsApiAirportGetResponses];

export type GetTestApiTestGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/test';
};

export type GetTestApiTestGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApiSearchFlightApiFlightGetData = {
    body?: never;
    path?: never;
    query: {
        origin: string;
        destination: string;
        date: string;
    };
    url: '/api/flight';
};

export type ApiSearchFlightApiFlightGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiSearchFlightApiFlightGetError = ApiSearchFlightApiFlightGetErrors[keyof ApiSearchFlightApiFlightGetErrors];

export type ApiSearchFlightApiFlightGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: 'http://127.0.0.1:8000' | (string & {});
};