// This file is auto-generated by @hey-api/openapi-ts

export type ApiCheckout = {
    id: string;
};

export type GetPayment = {
    name: string;
    lastname: string;
    gender: string;
    country: string;
    birthday: string;
    identityType: GetPaymentIdentity;
    contact: GetPaymentContact;
};

export type GetPaymentContact = {
    prefix: string;
    name: string;
    lastname: string;
    email: string;
    countryCode: string;
    phoneNumber: string;
};

export type GetPaymentIdentity = {
    type: string;
    number: string;
    out_date: string;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type LoginModel = {
    username: string;
    password: string;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApiCheckoutApiCheckoutPostData = {
    body: ApiCheckout;
    path?: never;
    query?: never;
    url: '/api_checkout';
};

export type ApiCheckoutApiCheckoutPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiCheckoutApiCheckoutPostError = ApiCheckoutApiCheckoutPostErrors[keyof ApiCheckoutApiCheckoutPostErrors];

export type ApiCheckoutApiCheckoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPaymentApiPaymentPostData = {
    body: GetPayment;
    path?: never;
    query?: never;
    url: '/api_payment';
};

export type GetPaymentApiPaymentPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPaymentApiPaymentPostError = GetPaymentApiPaymentPostErrors[keyof GetPaymentApiPaymentPostErrors];

export type GetPaymentApiPaymentPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LoginApiLoginPostData = {
    body: LoginModel;
    path?: never;
    query?: never;
    url: '/api_login';
};

export type LoginApiLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiLoginPostError = LoginApiLoginPostErrors[keyof LoginApiLoginPostErrors];

export type LoginApiLoginPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAirportApiGetAirportGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api_get_airport';
};

export type GetAirportApiGetAirportGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTestApiTestGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api_test';
};

export type GetTestApiTestGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetFlightApiSearchFlightGetData = {
    body?: never;
    path?: never;
    query: {
        src: string;
        dest: string;
        date: string;
    };
    url: '/api_search_flight';
};

export type GetFlightApiSearchFlightGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFlightApiSearchFlightGetError = GetFlightApiSearchFlightGetErrors[keyof GetFlightApiSearchFlightGetErrors];

export type GetFlightApiSearchFlightGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: 'http://127.0.0.1:8000' | (string & {});
};