// This file is auto-generated by @hey-api/openapi-ts

export type AircraftResponse = {
    id: string;
    model: string;
};

export type Airport = {
    name: string;
    address: string;
    code: string;
};

export type BookingPaymentResponse = {
    payment_id: string;
    email: string;
};

export type CancelModel = {
    flight_route_id: string;
    booking_id: string;
};

export type CheckoutModel = {
    flight_id: string;
    uid: string;
    return_flight_id: string | null;
};

export type FlightResponse = {
    aircraft: AircraftResponse;
    route: FlightRouteResponse;
};

export type FlightRoutSchedule = {
    departure: string;
    arrival: string;
    duration: number;
};

export type FlightRouteResponse = {
    id: string;
    date: string;
    destination: Array<string>;
    origin: Array<string>;
    status: string;
    is_avaliable: boolean;
    price: number;
    schedule: FlightScheduleResponse;
};

export type FlightScheduleResponse = {
    arrival: string;
    day_of_week: Array<number>;
    departure: string;
    duration: number;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type LoginResponse = {
    id: string;
    name: string;
    email: string;
};

export type PassengerModel = {
    name: string;
    lastname: string;
    gender: string;
    country: string;
    birthday: string;
    identity: PaymentIdentity;
};

export type PaymentContact = {
    prefix: string;
    name: string;
    lastname: string;
    email: string;
    country_code: string;
    phone_number: string;
};

export type PaymentGateway = {
    payment_id: string;
    user_id: string;
    type: string;
    number: string;
    out_date: string;
    cvv: string;
    holder_name: string;
};

export type PaymentIdentity = {
    type: string;
    number: string;
    out_date: string | null;
};

export type PaymentModel = {
    user_id: string;
    seat_class: string;
    flight_route_id: string;
    flight_route_back_id: string | null;
    passengers: Array<PassengerModel>;
    contact: PaymentContact;
};

export type TicketResponse = {
    ticket_id: string;
    passenger_name: string;
    seat: string;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type AirlinewaApiRoutesBookingBookingResponse = {
    id: string;
    user_id: string;
    date: string;
    departure: string;
    origin: Array<string>;
    destination: Array<string>;
    arrive: string;
    status: string;
};

export type AirlinewaApiRoutesTicketBookingResponse = {
    flight_id: string;
    booking_id: string;
    user: string;
    flight: AirlinewaApiRoutesTicketFlightRoute;
    tickets: Array<TicketResponse>;
    gate: string;
    boarding_time: string;
    flight_date: string;
};

export type AirlinewaApiRoutesTicketFlightRoute = {
    origin: string;
    dest: string;
};

export type AirlinewaModelsFlightRoute = {
    id: string;
    origin: Array<string>;
    destination: Array<string>;
    schedule: FlightRoutSchedule;
    date: string;
    price: number | null;
};

export type AirportGetAirportsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/airport/';
};

export type AirportGetAirportsResponses = {
    /**
     * Successful Response
     */
    200: Array<Airport>;
};

export type AirportGetAirportsResponse = AirportGetAirportsResponses[keyof AirportGetAirportsResponses];

export type UserUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/';
};

export type UserUsersResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type AuthLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
    /**
     * Successful Response
     */
    200: LoginResponse;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type FlightSearchFlightData = {
    body?: never;
    path?: never;
    query: {
        tripe_type: string;
        seat_class: string;
        origin: string;
        destination: string;
        date: string;
        adult: number;
        child: number;
        kid: number;
    };
    url: '/api/flight/';
};

export type FlightSearchFlightErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FlightSearchFlightError = FlightSearchFlightErrors[keyof FlightSearchFlightErrors];

export type FlightSearchFlightResponses = {
    /**
     * Successful Response
     */
    200: Array<AirlinewaModelsFlightRoute>;
};

export type FlightSearchFlightResponse = FlightSearchFlightResponses[keyof FlightSearchFlightResponses];

export type FlightFindFlightData = {
    body?: never;
    path: {
        flight_number: string;
    };
    query: {
        date: string;
    };
    url: '/api/flight/{flight_number}';
};

export type FlightFindFlightErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FlightFindFlightError = FlightFindFlightErrors[keyof FlightFindFlightErrors];

export type FlightFindFlightResponses = {
    /**
     * Successful Response
     */
    200: FlightResponse;
};

export type FlightFindFlightResponse = FlightFindFlightResponses[keyof FlightFindFlightResponses];

export type BookingBookingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/booking/';
};

export type BookingBookingsResponses = {
    /**
     * Successful Response
     */
    200: Array<AirlinewaApiRoutesBookingBookingResponse>;
};

export type BookingBookingsResponse = BookingBookingsResponses[keyof BookingBookingsResponses];

export type BookingBookingData = {
    body?: never;
    path: {
        booking_number: string;
    };
    query?: never;
    url: '/api/booking/{booking_number}';
};

export type BookingBookingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BookingBookingError = BookingBookingErrors[keyof BookingBookingErrors];

export type BookingBookingResponses = {
    /**
     * Successful Response
     */
    200: AirlinewaApiRoutesBookingBookingResponse;
};

export type BookingBookingResponse = BookingBookingResponses[keyof BookingBookingResponses];

export type PaymentPaymentsData = {
    body: PaymentModel;
    path?: never;
    query?: never;
    url: '/api/payment/';
};

export type PaymentPaymentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PaymentPaymentsError = PaymentPaymentsErrors[keyof PaymentPaymentsErrors];

export type PaymentPaymentsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PaymentCheckoutData = {
    body: CheckoutModel;
    path?: never;
    query?: never;
    url: '/api/payment/checkout';
};

export type PaymentCheckoutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PaymentCheckoutError = PaymentCheckoutErrors[keyof PaymentCheckoutErrors];

export type PaymentCheckoutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PaymentPaymentCancelData = {
    body: CancelModel;
    path?: never;
    query?: never;
    url: '/api/payment/cancel';
};

export type PaymentPaymentCancelErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PaymentPaymentCancelError = PaymentPaymentCancelErrors[keyof PaymentPaymentCancelErrors];

export type PaymentPaymentCancelResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PaymentPaymentGatewayData = {
    body: PaymentGateway;
    path?: never;
    query?: never;
    url: '/api/payment/payment_gateway';
};

export type PaymentPaymentGatewayErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PaymentPaymentGatewayError = PaymentPaymentGatewayErrors[keyof PaymentPaymentGatewayErrors];

export type PaymentPaymentGatewayResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PaymentPaymentSuccessData = {
    body?: never;
    path?: never;
    query: {
        booking_id: string;
    };
    url: '/api/payment/success';
};

export type PaymentPaymentSuccessErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PaymentPaymentSuccessError = PaymentPaymentSuccessErrors[keyof PaymentPaymentSuccessErrors];

export type PaymentPaymentSuccessResponses = {
    /**
     * Successful Response
     */
    200: BookingPaymentResponse;
};

export type PaymentPaymentSuccessResponse = PaymentPaymentSuccessResponses[keyof PaymentPaymentSuccessResponses];

export type UtilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        email_to: string;
    };
    url: '/api/utils/test-email';
};

export type UtilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UtilsTestEmailError = UtilsTestEmailErrors[keyof UtilsTestEmailErrors];

export type UtilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/utils/health-check';
};

export type UtilsHealthCheckResponses = {
    /**
     * Successful Response
     */
    200: boolean;
};

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses];

export type TicketTicketData = {
    body?: never;
    path?: never;
    query: {
        booking_id: string;
    };
    url: '/api/ticket/';
};

export type TicketTicketErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TicketTicketError = TicketTicketErrors[keyof TicketTicketErrors];

export type TicketTicketResponses = {
    /**
     * Successful Response
     */
    200: AirlinewaApiRoutesTicketBookingResponse;
};

export type TicketTicketResponse = TicketTicketResponses[keyof TicketTicketResponses];

export type ClientOptions = {
    baseURL: 'http://127.0.0.1:8000' | (string & {});
};