// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zAirport = z.object({
    name: z.string(),
    address: z.string(),
    code: z.string()
});

export const zCheckoutModel = z.object({
    id: z.string()
});

export const zFlightRoutSchedule = z.object({
    departure: z.string(),
    arrival: z.string()
});

export const zFlightRoute = z.object({
    id: z.string(),
    origin: z.array(z.string()),
    destination: z.array(z.string()),
    schedule: zFlightRoutSchedule,
    date: z.string().datetime(),
    price: z.number().int()
});

export const zHttpValidationError = z.object({
    detail: z.array(z.object({
        loc: z.array(z.unknown()),
        msg: z.string(),
        type: z.string()
    })).optional()
});

export const zLoginModel = z.object({
    username: z.string(),
    password: z.string()
});

export const zPassenger = z.object({
    name: z.string(),
    lastname: z.string(),
    gender: z.string(),
    country: z.string(),
    birthday: z.string(),
    identity_type: z.object({
        type: z.string(),
        number: z.string(),
        out_date: z.string()
    })
});

export const zPaymentContact = z.object({
    prefix: z.string(),
    name: z.string(),
    lastname: z.string(),
    email: z.string(),
    country_code: z.string(),
    phone_number: z.string()
});

export const zPaymentIdentity = z.object({
    type: z.string(),
    number: z.string(),
    out_date: z.string()
});

export const zPaymentModel = z.object({
    user_id: z.string(),
    flight_route_id: z.string(),
    passengers: z.array(zPassenger),
    contact: zPaymentContact
});

export const zValidationError = z.object({
    loc: z.array(z.unknown()),
    msg: z.string(),
    type: z.string()
});

export const zAirportGetAirportsResponse = z.array(zAirport);

export const zFlightSearchFlightResponse = z.array(zFlightRoute);

export const zUtilsHealthCheckResponse = z.boolean();