// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zAircraftResponse = z.object({
    id: z.string(),
    model: z.string()
});

export const zAirport = z.object({
    name: z.string(),
    address: z.string(),
    code: z.string()
});

export const zBookingPaymentResponse = z.object({
    payment_id: z.string(),
    email: z.string()
});

export const zCancelModel = z.object({
    flight_route_id: z.string(),
    booking_id: z.string()
});

export const zCheckoutModel = z.object({
    flight_id: z.string(),
    uid: z.string(),
    return_flight_id: z.union([
        z.string(),
        z.null()
    ])
});

export const zFlightResponse = z.object({
    aircraft: zAircraftResponse,
    route: z.object({
        id: z.string(),
        date: z.string().datetime(),
        destination: z.array(z.string()),
        origin: z.array(z.string()),
        status: z.string(),
        is_avaliable: z.boolean(),
        price: z.number().int(),
        schedule: z.object({
            arrival: z.string(),
            day_of_week: z.array(z.number().int()),
            departure: z.string(),
            duration: z.number().int()
        })
    })
});

export const zFlightRoutSchedule = z.object({
    departure: z.string(),
    arrival: z.string(),
    duration: z.number().int()
});

export const zFlightRouteResponse = z.object({
    id: z.string(),
    date: z.string().datetime(),
    destination: z.array(z.string()),
    origin: z.array(z.string()),
    status: z.string(),
    is_avaliable: z.boolean(),
    price: z.number().int(),
    schedule: z.object({
        arrival: z.string(),
        day_of_week: z.array(z.number().int()),
        departure: z.string(),
        duration: z.number().int()
    })
});

export const zFlightScheduleResponse = z.object({
    arrival: z.string(),
    day_of_week: z.array(z.number().int()),
    departure: z.string(),
    duration: z.number().int()
});

export const zHttpValidationError = z.object({
    detail: z.array(z.object({
        loc: z.array(z.unknown()),
        msg: z.string(),
        type: z.string()
    })).optional()
});

export const zLoginRequest = z.object({
    email: z.string(),
    password: z.string()
});

export const zLoginResponse = z.object({
    id: z.string(),
    name: z.string(),
    email: z.string()
});

export const zPassengerModel = z.object({
    name: z.string(),
    lastname: z.string(),
    gender: z.string(),
    country: z.string(),
    birthday: z.string(),
    identity: z.object({
        type: z.string(),
        number: z.string(),
        out_date: z.union([
            z.string(),
            z.null()
        ])
    })
});

export const zPaymentContact = z.object({
    prefix: z.string(),
    name: z.string(),
    lastname: z.string(),
    email: z.string(),
    country_code: z.string(),
    phone_number: z.string()
});

export const zPaymentGateway = z.object({
    payment_id: z.string(),
    user_id: z.string(),
    type: z.string(),
    number: z.string(),
    out_date: z.string(),
    cvv: z.string(),
    holder_name: z.string()
});

export const zPaymentIdentity = z.object({
    type: z.string(),
    number: z.string(),
    out_date: z.union([
        z.string(),
        z.null()
    ])
});

export const zPaymentModel = z.object({
    user_id: z.string(),
    seat_class: z.string(),
    flight_route_id: z.string(),
    passengers: z.array(zPassengerModel),
    contact: zPaymentContact
});

export const zTicketResponse = z.object({
    ticket_id: z.string(),
    passenger_name: z.string(),
    seat: z.string()
});

export const zValidationError = z.object({
    loc: z.array(z.unknown()),
    msg: z.string(),
    type: z.string()
});

export const zAirlinewaApiRoutesBookingBookingResponse = z.object({
    id: z.string(),
    user_id: z.string(),
    date: z.string().datetime(),
    departure: z.string(),
    origin: z.array(z.string()),
    destination: z.array(z.string()),
    arrive: z.string(),
    status: z.string()
});

export const zAirlinewaApiRoutesTicketBookingResponse = z.object({
    flight_id: z.string(),
    booking_id: z.string(),
    user: z.string(),
    flight: z.object({
        origin: z.string(),
        dest: z.string()
    }),
    tickets: z.array(zTicketResponse),
    gate: z.string(),
    boarding_time: z.string(),
    flight_date: z.string()
});

export const zAirlinewaApiRoutesTicketFlightRoute = z.object({
    origin: z.string(),
    dest: z.string()
});

export const zAirlinewaModelsFlightRoute = z.object({
    id: z.string(),
    origin: z.array(z.string()),
    destination: z.array(z.string()),
    schedule: zFlightRoutSchedule,
    date: z.string().datetime(),
    price: z.union([
        z.number(),
        z.null()
    ])
});

export const zAirportGetAirportsResponse = z.array(zAirport);

export const zAuthLoginResponse = zLoginResponse;

export const zFlightSearchFlightResponse = z.array(zAirlinewaModelsFlightRoute);

export const zFlightFindFlightResponse = zFlightResponse;

export const zBookingBookingsResponse = z.array(zAirlinewaApiRoutesBookingBookingResponse);

export const zBookingBookingResponse = zAirlinewaApiRoutesBookingBookingResponse;

export const zPaymentPaymentSuccessResponse = zBookingPaymentResponse;

export const zUtilsHealthCheckResponse = z.boolean();

export const zTicketTicketResponse = zAirlinewaApiRoutesTicketBookingResponse;